### ISSUE TITLE
Epic for Python Challenges

### ISSUE THREAD

**Issue by koustuvsinha** [alayek/backend-challenges#9]
This is an Epic Issue to track development of Python Challenges. As per our [initial planning draft](https://docs.google.com/document/d/1lNi2bKms52uMtvwxn3znnspz08UUwuSTMYXKDyiUd_k/edit), we need submissions for these challenges first : 
- [ ] [Import `this`](https://repl.it/CRkd/0)
- [ ] [Simple Print Statement](https://repl.it/CRkq/1)
- [ ] [Basic Maths](https://repl.it/CRlI/0)
- [ ] [More Printing with numbers](https://repl.it/CRkq/10)
- [ ] [Strings in Python](https://repl.it/CRmC/0)
- [ ] [Conditional Statements](https://repl.it/C3YU/0)
- [ ] [Sets & Arrays]()
- [ ] Tuples
- [ ] Simple Functions
- [ ] Complex Functions, multiple returns, named parameter
- [ ] Lists - Basic (just the lists, what they look like)
- [ ] Lists - Intermediate (the useful functions - append, join, len etc.)
- [ ] Lists - Advanced (enumeration, iterators)
- [ ] Dictionaries - Basic (What is a valid dict, what they look like)
- [ ] Dictionaries - Intermediate (dict functions, key and errors)
- [ ] Dictionaries - Advanced (enumeration over two dimensions - key and value)
- [ ] Modules, Classes and Objects Basics
- [ ] Modules, Classes and Objects Intermediate
- [ ] Modules, Classes and Objects Advanced
- [ ] Basic Testing
- [ ] The main function and if-name-main syntax

**Comment by byteknacker** [comment]
Hey, what is this repo about? Is it related to FCC curriculum?

**Comment by alayek** [comment]
Hey @byteknacker, yeah this repo has been around for a while. This is to coordinate our in-browser challenges. We just re-animated the repo today. I have been meaning to talk to you about it.

Your input would surely be valuable! However, we need your undivided attention on the vagrant repo now and take that to maturity. If you want to contribute to this, it should not come at the cost of your vagrant work.

**Comment by byteknacker** [comment]
@alayek I think I will contribute to this one after one or two release has been done for fcc-python-vagrant. I let you know when I can dedicate for this project.

**Comment by erictleung** [comment]
@alayek just to be clear, we're using Python 3? I looked at the repl you created for importing `this` and it used Python 3.5. I was about to suggest using Python 3 over Python 2 considering Python 2 will not be maintained in the near future.

**Comment by alayek** [comment]
@erictleung yes, we are going to use Python 3. Our course is for  beginners in Python, and the Python 2 vs. 3 debate would tell you that if you are starting in Python now, just go with Python 3.

In enterprise, some legacy applications still needs to be maintained in Python 2.7. We will see the response from campers, and if there is a high demand for Python 2.7, we would probably shadow this curriculum to form one on Python 2 as well.

But we don't have anything other than plans for Python 3 right now.
